### ISSUE TITLE
Exception 'not found' when INI config file not found

### ISSUE THREAD

**Issue by pjotrek-b** [ArkThis/cinbox#22]
The following error is shown when starting cinbox.php, pointing to an invalid (non-CInbox) folder:

```
Initializing Inbox...

PHP Fatal error:  Uncaught Error: Class 'ArkThis\CInbox\Exception' not found in /opt/cinbox/src/lib/CInbox/CIConfig.php:320
Stack trace:
#0 /opt/cinbox/src/lib/CInbox/CInbox.php(294): ArkThis\CInbox\CIConfig->setConfigFile('./cinbox.ini')
#1 /opt/cinbox/src/cinbox.php(291): ArkThis\CInbox\CInbox->setConfigFile('./cinbox.ini')
#2 /opt/cinbox/src/cinbox.php(321): initInbox()
#3 {main}
  thrown in /opt/cinbox/src/lib/CInbox/CIConfig.php on line 320
```

**Comment by pjotrek-b** [comment]
Fixed in 06e5bbd5eacd7e413067e79c1f32ce15a96de4a9:
Exception class was in "the wrong" PHP namespace.
